make 1:
	g++ -I/usr/include/freetype2 -o circles circle_animation_1.cpp -lglut -lGL -lcurl -std=c++0x -pthread
make 2:
	g++ -I/usr/include/freetype2 -o circles circle_animation_2.cpp -lglut -lGL -lcurl -std=c++0x -pthread
